# Generated by Django 3.0.4 on 2020-04-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_groupdata_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupData',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
